window.showToast = function(message, type = 'default') { const container = document.getElementById('toast-container'); if (!container) return; const toast = document.createElement('div'); toast.className = `toast ${type === 'success' ? 'toast-success' : type === 'danger' ? 'toast-danger' : ''}`; toast.textContent = message; container.appendChild(toast); setTimeout(() => toast.remove(), 3200); };

class App {
  constructor() { this.navBtns = document.querySelectorAll('.nav-tab-btn'); this.pages = document.querySelectorAll('.page-section'); this.started = false; this.bindAuth(); this.init(); }
  async init() { await window.cloudManager.initialize(); this.bindCloudModalEvents(); this.renderAuth(); if (window.cloudManager.session) await this.start(); }
  bindAuth() {
    document.getElementById('sign-in-form')?.addEventListener('submit', async event => { event.preventDefault(); const error = document.getElementById('auth-error'); error.textContent = ''; try { await window.cloudManager.signIn(document.getElementById('sign-in-email').value.trim(), document.getElementById('sign-in-password').value); await this.start(); } catch (err) { error.textContent = err.message || 'Sign-in failed. Please check your details.'; } });
    document.getElementById('password-toggle')?.addEventListener('click', () => { const input = document.getElementById('sign-in-password'); input.type = input.type === 'password' ? 'text' : 'password'; document.getElementById('password-toggle').textContent = input.type === 'password' ? 'Show' : 'Hide'; });
    document.getElementById('auth-setup-btn')?.addEventListener('click', () => this.openCloudModal());
    document.getElementById('sign-out-btn')?.addEventListener('click', async () => { await window.cloudManager.signOut(); location.reload(); });
    window.addEventListener('auth-state-changed', async () => { this.renderAuth(); if (window.cloudManager.session && !this.started) await this.start(); });
  }
  renderAuth() { const signedIn = Boolean(window.cloudManager.session); document.getElementById('auth-screen').classList.toggle('hidden', signedIn); document.getElementById('sign-out-btn').style.display = signedIn ? 'inline-flex' : 'none'; document.getElementById('auth-setup-btn').style.display = window.cloudManager.isConfigured ? 'none' : 'inline-block'; document.body.classList.toggle('authenticated', signedIn); }
  async start() { if (this.started) return; this.started = true; this.bindNavEvents(); this.switchPage(location.hash.replace('#', '') || 'home'); await window.appDB.ensureDb(); if (window.contactsManager) await window.contactsManager.load(); if (window.filesManager) await window.filesManager.load(); if (window.hostelManager) await window.hostelManager.load(); if (window.studentCounterManager) { window.studentCounterManager.loadPersistedCounts(); window.studentCounterManager.loadHistory(); } this.updateHomeStats(); window.cloudManager.updateStatusBadge(); }
  bindNavEvents() { this.navBtns.forEach(btn => btn.addEventListener('click', () => this.switchPage(btn.dataset.page))); window.addEventListener('hashchange', () => this.switchPage(location.hash.replace('#', '') || 'home', false)); }
  switchPage(pageId, updateHash = true) { const valid = ['home', 'contacts', 'files', 'hostel', 'counter']; if (!valid.includes(pageId)) pageId = 'home'; this.navBtns.forEach(btn => btn.classList.toggle('active', btn.dataset.page === pageId)); this.pages.forEach(page => page.classList.toggle('active', page.id === `page-${pageId}`)); if (updateHash && location.hash !== `#${pageId}`) location.hash = pageId; window.scrollTo({ top: 0, behavior: 'smooth' }); if (pageId === 'home') this.updateHomeStats(); }
  updateHomeStats() { const set = (id, value) => { const el = document.getElementById(id); if (el) el.textContent = value; }; set('stat-students-count', window.hostelManager?.students?.length || 0); set('stat-contacts-count', window.contactsManager?.contacts?.length || 0); set('stat-files-count', window.filesManager?.files?.length || 0); const counts = window.studentCounterManager?.counts || {}; set('stat-headcount-total', (counts.y1 || 0) + (counts.y2 || 0) + (counts.y3 || 0) + (counts.sports || 0)); }
  bindCloudModalEvents() { const modal = document.getElementById('cloud-modal'), textarea = document.getElementById('supabase-config-input'); document.getElementById('cloud-sync-btn')?.addEventListener('click', () => this.openCloudModal()); document.getElementById('cloud-modal-close')?.addEventListener('click', () => this.closeCloudModal()); document.getElementById('cloud-modal-cancel')?.addEventListener('click', () => this.closeCloudModal()); document.getElementById('cloud-save-btn')?.addEventListener('click', async () => { try { const [url, anonKey] = textarea.value.trim().split(/\r?\n/).map(x => x.trim()).filter(Boolean); await window.cloudManager.saveConfig({ url, anonKey }); window.showToast('Supabase saved. You can now sign in.', 'success'); this.closeCloudModal(); this.renderAuth(); } catch (err) { window.showToast(err.message, 'danger'); } }); document.getElementById('cloud-disconnect-btn')?.addEventListener('click', () => { window.cloudManager.clearConfig(); location.reload(); }); document.getElementById('cloud-sync-now-btn')?.addEventListener('click', async () => { const ok = await window.appDB.syncLocalToCloud(); window.showToast(ok ? 'Local data uploaded.' : 'Sign in before uploading.', ok ? 'success' : 'danger'); }); }
  openCloudModal() { const modal = document.getElementById('cloud-modal'), textarea = document.getElementById('supabase-config-input'); if (window.cloudManager.isConfigured) { textarea.value = `${window.cloudManager.config.url}\n${window.cloudManager.config.anonKey}`; document.getElementById('cloud-disconnect-btn').style.display = 'inline-flex'; document.getElementById('cloud-sync-now-btn').style.display = window.cloudManager.session ? 'inline-flex' : 'none'; } modal.classList.add('open'); }
  closeCloudModal() { document.getElementById('cloud-modal')?.classList.remove('open'); }
}
document.addEventListener('DOMContentLoaded', () => { window.app = new App(); });
