const SUPABASE_URL = 'https://ikrblrjpusstmnmzdghc.supabase.co';

const SUPABASE_KEY =
  'sb_publishable_iFD4E9u-2qwb5hH49aKBQg_1vaqVYXY';

const supabaseClient = window.supabase.createClient(
  SUPABASE_URL,
  SUPABASE_KEY
);

async function login() {
  const email = document.getElementById('loginEmail').value.trim();
  const password = document.getElementById('loginPassword').value;

  const errorEl = document.getElementById('loginError');

  errorEl.textContent = '';

  if (!email || !password) {
    errorEl.textContent = 'Please enter email and password.';
    return;
  }

  const { error } = await supabaseClient.auth.signInWithPassword({
    email,
    password
  });

  if (error) {
    errorEl.textContent = error.message;
    return;
  }

  await startApp();
}

async function logout() {
  await supabaseClient.auth.signOut();
  location.reload();
}

async function startApp() {
  const {
    data: { session }
  } = await supabaseClient.auth.getSession();

  const loginScreen = document.getElementById('loginScreen');

  if (!session) {
    loginScreen.style.display = 'flex';
    return;
  }

  loginScreen.style.display = 'none';

  render();
}
const state={page:'home',contactFilter:'All',contactSort:'name-asc',fileFilter:'All',fileSort:'name-asc',selectedBatch:null,selectedStudent:null,contacts:[{id:1,name:'Aarav Sharma',category:'Fathers',phone:'+91 98765 43210',secondary:'+91 87654 32109'},{id:2,name:'Priya Sharma',category:'Sisters',phone:'+91 91234 56789',secondary:'+91 98765 70655'},{id:3,name:'Suresh Driver',category:'Driver',phone:'+91 90011 22334',secondary:'+91 88776 55443'},{id:4,name:'Rajesh Electrician',category:'Electrician',phone:'+91 98765 54321',secondary:'+91 87654 44322'},{id:5,name:'Lakshmi Kitchen',category:'Kitchen',phone:'+91 92000 45678',secondary:'+91 99887 66554'}],files:[{id:1,name:'Student Handbook.pdf',category:'PDF',date:'12 Apr 2025',size:'2.4 MB'},{id:2,name:'Fee Structure.docx',category:'Word',date:'10 Apr 2025',size:'1.2 MB'},{id:3,name:'Timetable.xlsx',category:'Excel',date:'8 Apr 2025',size:'850 KB'},{id:4,name:'Important Notice.pdf',category:'PDF',date:'5 Apr 2025',size:'1.8 MB'},{id:5,name:'Office Circular.docx',category:'Word',date:'2 Apr 2025',size:'1.1 MB'},{id:6,name:'Sports Schedule.xlsx',category:'Excel',date:'28 Mar 2025',size:'650 KB'}],students:{'Batch 1 — 1st Years':[{id:101,name:'Aarav Sharma',course:'B.Tech - CSE',father:'Rajesh Sharma',fatherPhone:'+91 98765 12345',mother:'Suman Sharma',motherPhone:'+91 87654 98765',phone:'+91 98765 43210',photo:''},{id:102,name:'Rohan Singh',course:'B.Tech - Mechanical',father:'Vijay Singh',fatherPhone:'+91 90000 11223',mother:'Anita Singh',motherPhone:'+91 90000 44556',phone:'+91 90000 77889',photo:''},{id:103,name:'Neha Patel',course:'B.Tech - ECE',father:'Mahesh Patel',fatherPhone:'+91 90000 12345',mother:'Kiran Patel',motherPhone:'+91 90000 54321',phone:'+91 90000 98765',photo:''},{id:104,name:'Aditya Verma',course:'B.Tech - Civil',father:'Sanjay Verma',fatherPhone:'+91 90123 45678',mother:'Pooja Verma',motherPhone:'+91 90123 87654',phone:'+91 90123 11111',photo:''},{id:105,name:'Pooja Kumari',course:'B.Tech - CSE',father:'Ramesh Kumar',fatherPhone:'+91 90222 11111',mother:'Sunita Kumari',motherPhone:'+91 90222 33333',phone:'+91 90222 55555',photo:''}], 'Batch 2 — 2nd Years':[], 'Batch 3 — 3rd Years':[], 'Batch 4 — Sports':[]},counters:{'Batch 1 — 1st Years':{Morning:24,Afternoon:22,Evening:20},'Batch 2 — 2nd Years':{Morning:18,Afternoon:16,Evening:14},'Batch 3 — 3rd Years':{Morning:26,Afternoon:24,Evening:22},'Batch 4 — Sports':{Morning:28,Afternoon:20,Evening:18}}};
const $=s=>document.querySelector(s), content=$('#appContent');const categories=['All','Fathers','Sisters','Driver','Electrician','Kitchen','Office','TC Staff','Other'];
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function nav(page){state.page=page;state.selectedBatch=null;state.selectedStudent=null;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const heads={home:['WELCOME','Welcome','Manage · Connect · Organize'],contacts:['DIRECTORY','Contacts','People, numbers and quick calls'],files:['DOCUMENTS','Files','Everything organized in one place'],hostel:['HOSTEL','Hostel','Students · Years · Sports'],counter:['DAILY FOOD','Student Counter','Morning · Afternoon · Evening']};const h=heads[page];$('#pageEyebrow').textContent=h[0];$('#pageTitle').textContent=h[1];$('#pageSubtitle').textContent=h[2];render()}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>nav(b.dataset.page));$('#pageDate').textContent=new Date().toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'});
function render(){({home:home,contacts:contacts,files:files,hostel:hostel,counter:counter})[state.page]()}
function home(){const contactCount=state.contacts.length, fileCount=state.files.length, batchCount=Object.keys(state.students).length, total=Object.values(state.counters).reduce((a,b)=>a+Object.values(b).reduce((x,y)=>x+y,0),0);content.innerHTML=`<h2 class="quick-title">Quick Overview</h2><div class="overview"><div class="overview-card orange"><div class="mini-icon">♧</div><span>Total Contacts</span><strong>${contactCount}</strong></div><div class="overview-card blue"><div class="mini-icon">▣</div><span>Files Uploaded</span><strong>${fileCount}</strong></div><div class="overview-card purple"><div class="mini-icon">♜</div><span>Hostel Batches</span><strong>${batchCount}</strong></div><div class="overview-card green"><div class="mini-icon">♜</div><span>Today's Count</span><strong>${total}</strong></div></div><div class="action-grid"><button class="action-tile tile-orange" data-go="home"><div class="tile-icon">⌂</div><strong>Home</strong></button><button class="action-tile tile-green" data-go="contacts"><div class="tile-icon">♧</div><strong>Contacts</strong></button><button class="action-tile tile-blue" data-go="files"><div class="tile-icon">▣</div><strong>Files</strong></button><button class="action-tile tile-purple" data-go="hostel"><div class="tile-icon">♜</div><strong>Hostel</strong></button><button class="action-tile tile-gold" data-go="counter"><div class="tile-icon">♜</div><strong>Counter</strong></button></div>`;content.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>nav(b.dataset.go))}
async function loadContacts() {
  const { data, error } = await supabaseClient
    .from('contacts')
    .select('*')
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Failed to load contacts:', error);
    return;
  }

  state.contacts = data;
}

async function contacts(){await loadContacts();let list=state.contacts.filter(c=>state.contactFilter==='All'||c.category===state.contactFilter);const q=($('#contactSearch')?.value||'').toLowerCase();list=list.filter(c=>`${c.name} ${c.category} ${c.phone} ${c.secondary||''}`.toLowerCase().includes(q));list.sort((a,b)=>state.contactSort==='name-desc'?b.name.localeCompare(a.name):state.contactSort==='category'?a.category.localeCompare(b.category)||a.name.localeCompare(b.name):a.name.localeCompare(b.name));content.innerHTML=`<div class="section-head"><div><h2>Contacts</h2><p>${state.contacts.length} saved contacts</p></div><button class="primary" id="addContact">＋ Add Contact</button></div><div class="search-row"><input class="search" id="contactSearch" placeholder="⌕  Search contacts..." value="${esc(q)}"><button class="filter-btn" title="Filter">▽</button></div><div class="chips">${categories.map(c=>`<button class="chip ${state.contactFilter===c?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('')}</div><div class="sort-row"><span class="sort-label">Sort contacts by</span><select class="sort-select" id="contactSort"><option value="name-asc">Name A–Z</option><option value="name-desc">Name Z–A</option><option value="category">Category</option></select></div><div class="cards" id="contactList">${list.map(c=>`<article class="card contact-card"><div class="avatar">${esc(c.name[0])}</div><div class="contact-main"><h3>${esc(c.name)}</h3><p>${esc(c.category)}</p><p>${esc(c.phone)}${c.secondary?' · '+esc(c.secondary):''}</p><div class="contact-actions"><button class="round-call" data-call="${esc(c.phone)}">☎ Call</button><button class="contact-edit" data-edit-contact="${c.id}">✎ Edit</button><button class="contact-delete" data-delete-contact="${c.id}">⌫ Delete</button></div></div></article>`).join('')||'<div class="card"><p>No contacts found.</p></div>'}</div>`;$('#contactSort').value=state.contactSort;$('#contactSearch').oninput=()=>contacts();$('#contactSort').onchange=e=>{state.contactSort=e.target.value;contacts()};content.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.contactFilter=b.dataset.cat;contacts()});content.querySelectorAll('[data-call]').forEach(b=>b.onclick=()=>location.href='tel:'+b.dataset.call);content.querySelectorAll('[data-edit-contact]').forEach(b=>b.onclick=()=>contactModal(+b.dataset.editContact));content.querySelectorAll('[data-delete-contact]').forEach(b=>b.onclick=()=>deleteContact(+b.dataset.deleteContact));$('#addContact').onclick=()=>contactModal()}
function contactModal(id){const c=id?state.contacts.find(x=>x.id===id):null;modal(`<h2>${id?'Edit Contact':'Add Contact'}</h2><div class="form-grid"><div class="field"><label>Name</label><input id="cName" value="${esc(c?.name||'')}"></div><div class="field"><label>Category</label><select id="cCat">${categories.slice(1).map(v=>`<option ${c?.category===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Primary Phone</label><input id="cPhone" inputmode="tel" value="${esc(c?.phone||'')}"></div><div class="field"><label>Secondary Phone (optional)</label><input id="cSecond" inputmode="tel" value="${esc(c?.secondary||'')}"></div></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" id="saveContact">${id?'Save Changes':'Save Contact'}</button></div>`);$('#saveContact').onclick=async()=>{const x={id:id||Date.now(),name:$('#cName').value.trim(),category:$('#cCat').value,phone:$('#cPhone').value.trim(),secondary:$('#cSecond').value.trim()};if(!x.name||!x.phone)return alert('Enter name and primary phone.');if(id){const { error } = await supabaseClient.from('contacts').update({name:x.name,category:x.category,phone:x.phone,secondary:x.secondary}).eq('id',id);if(error){alert(error.message);return}closeModal();await contacts();return}const {error}=await supabaseClient.from('contacts').insert({name:x.name,category:x.category,phone:x.phone,secondary:x.secondary});if(error){alert(error.message);return}await contacts();closeModal()}}
async function deleteContact(id){if(!confirm('Delete this contact?'))return;const {error}=await supabaseClient.from('contacts').delete().eq('id',id);if(error){alert(error.message);return}await contacts()}
function files(){let list=state.files.filter(f=>state.fileFilter==='All'||f.category===state.fileFilter);list.sort((a,b)=>state.fileSort==='name-desc'?b.name.localeCompare(a.name):state.fileSort==='date'?new Date(b.date)-new Date(a.date):a.name.localeCompare(b.name));content.innerHTML=`<div class="section-head"><div><h2>Files</h2><p>${state.files.length} documents stored</p></div><button class="primary" id="uploadFile">＋ Upload File</button></div><div class="search-row"><input class="search" id="fileSearch" placeholder="⌕  Search files..."><button class="filter-btn">▽</button></div><div class="chips">${['All','PDF','Word','Excel','Other'].map(c=>`<button class="chip ${state.fileFilter===c?'active':''}" data-file-cat="${c}">${c}</button>`).join('')}</div><div class="sort-row"><span class="sort-label">Sort files by</span><select class="sort-select" id="fileSort"><option value="name-asc">Name A–Z</option><option value="name-desc">Name Z–A</option><option value="date">Newest first</option></select></div><div class="cards" id="fileList">${list.map(f=>`<article class="card file-card"><div class="file-icon ${f.category==='Word'?'word':f.category==='Excel'?'excel':''}">${f.category==='PDF'?'PDF':f.category==='Word'?'W':'X'}</div><div><h3>${esc(f.name)}</h3><div class="file-meta"><span>${f.category}</span><span>· ${f.size}</span><span>· ${f.date}</span></div></div><div class="file-actions"><button class="tiny">↓</button><button class="tiny delete" data-file-delete="${f.id}">▥</button></div></article>`).join('')||'<div class="card"><p>No files found.</p></div>'}</div>`;$('#fileSort').value=state.fileSort;$('#fileSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#fileList .file-card').forEach(card=>card.style.display=card.innerText.toLowerCase().includes(q)?'grid':'none')};$('#fileSort').onchange=e=>{state.fileSort=e.target.value;files()};content.querySelectorAll('[data-file-cat]').forEach(b=>b.onclick=()=>{state.fileFilter=b.dataset.fileCat;files()});content.querySelectorAll('[data-file-delete]').forEach(b=>b.onclick=()=>{state.files=state.files.filter(f=>f.id!==+b.dataset.fileDelete);files()});$('#uploadFile').onclick=fileModal}
function fileModal(){modal(`<h2>Upload File</h2><div class="form-grid"><div class="field"><label>File</label><input id="fileInput" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.txt"></div><div class="field"><label>Category</label><select id="fileCat"><option>PDF</option><option>Word</option><option>Excel</option><option>Other</option></select></div></div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" id="saveFile">Add File</button></div>`);$('#saveFile').onclick=()=>{const f=$('#fileInput').files[0];if(!f)return alert('Choose a file.');state.files.unshift({id:Date.now(),name:f.name,category:$('#fileCat').value,date:new Date().toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}),size:(f.size/1024/1024).toFixed(1)+' MB'});closeModal();files()}}
function hostel(){const bs=Object.keys(state.students);content.innerHTML=`<div class="section-head"><div><h2>Hostel</h2><p>Select a batch to view students</p></div><button class="secondary">⌕</button></div><div class="batch-grid">${bs.map((b,i)=>`<button class="batch-card ${['batch1','batch2','batch3','batch4'][i]}" data-batch="${esc(b)}"><div class="batch-icon">${['🎓','📘','🎓','🏆'][i]}</div><h3>${b.replace(' — ',' · ')}</h3><p>Batch ${i+1} · ${state.students[b].length} Students</p></button>`).join('')}</div>`;content.querySelectorAll('[data-batch]').forEach(b=>b.onclick=()=>students(b.dataset.batch))}
function students(batch){state.selectedBatch=batch;const list=state.students[batch];content.innerHTML=`<div class="section-head"><div><h2>${batch.split(' — ')[1]}</h2><div class="batch-pill">♟ Batch ${Object.keys(state.students).indexOf(batch)+1}</div></div><button class="primary" id="addStudent">＋ Add Student</button></div><div class="student-toolbar"><button class="secondary" id="backHostel">← Hostel</button><span class="sort-label">${list.length} student(s)</span></div><div class="search-row"><input class="search" id="studentSearch" placeholder="⌕  Search students..."></div><div class="student-list" id="studentList">${list.map(s=>`<button class="student" data-student="${s.id}"><div class="avatar">${s.photo?`<img src="${s.photo}" alt="">`:esc(s.name[0])}</div><div class="student-info"><h3>${esc(s.name)}</h3><p>${esc(s.course)}</p></div><div class="student-arrow">›</div></button>`).join('')||'<div class="card"><p>No students added yet.</p></div>'}</div>`;$('#backHostel').onclick=hostel;$('#addStudent').onclick=()=>studentModal(batch);content.querySelectorAll('[data-student]').forEach(b=>b.onclick=()=>studentDetails(batch,+b.dataset.student));$('#studentSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('#studentList .student').forEach(x=>x.style.display=x.innerText.toLowerCase().includes(q)?'grid':'none')}}
function studentDetails(batch,id){const s=state.students[batch].find(x=>x.id===id);if(!s)return;state.selectedStudent=id;content.innerHTML=`<button class="secondary" id="backStudents">← ${batch.split(' — ')[1]}</button><div style="height:10px"></div><article class="profile"><div class="profile-top"><div class="profile-photo">${s.photo?`<img src="${s.photo}" alt="">`:esc(s.name[0])}</div><div><h2>${esc(s.name)}</h2><div class="meta">▣ ${esc(s.course)}<br>♟ ${esc(batch.replace(' — ',' · '))}</div></div></div><div class="profile-actions"><button class="profile-call" data-call="${esc(s.phone)}">☎<br>Call Student</button><button class="profile-call blue" data-call="${esc(s.fatherPhone)}">☎<br>Call Father</button><button class="profile-call purple" data-call="${esc(s.motherPhone)}">☎<br>Call Mother</button></div><div class="info-list"><div class="info-row"><span>♟ Father's Name</span><span>${esc(s.father)}<br>${esc(s.fatherPhone)}</span></div><div class="info-row"><span>♟ Mother's Name</span><span>${esc(s.mother)}<br>${esc(s.motherPhone)}</span></div><div class="info-row"><span>▣ Course</span><span>${esc(s.course)}</span></div><div class="info-row"><span>♟ Batch</span><span>${esc(batch.replace(' — ',' · '))}</span></div></div><div class="profile-footer"><button class="primary" id="editStudent">✎ Edit Details</button><button class="danger" id="deleteStudent">Delete</button></div></article>`;$('#backStudents').onclick=()=>students(batch);content.querySelectorAll('[data-call]').forEach(b=>b.onclick=()=>location.href='tel:'+b.dataset.call);$('#editStudent').onclick=()=>studentModal(batch,id);$('#deleteStudent').onclick=()=>{state.students[batch]=state.students[batch].filter(x=>x.id!==id);students(batch)}}
function studentModal(batch,id){const s=(state.students[batch]||[]).find(x=>x.id===id)||{name:'',course:'',father:'',fatherPhone:'',mother:'',motherPhone:'',phone:'',photo:''};modal(`<h2>${id?'Edit Student':'Add Student'}</h2><div class="form-grid"><div class="field"><label>Student Photo</label><div class="photo-picker"><div class="preview" id="preview">${s.photo?`<img src="${s.photo}" alt="">`:'Photo'}</div><input id="sPhoto" type="file" accept="image/*"></div></div>${[['Name','sName','name'],['Course','sCourse','course'],["Father's Name",'sFather','father'],["Father's Number",'sFatherPhone','fatherPhone'],["Mother's Name",'sMother','mother'],["Mother's Number",'sMotherPhone','motherPhone'],["Student's Number",'sPhone','phone']].map(x=>`<div class="field"><label>${x[0]}</label><input id="${x[1]}" value="${esc(s[x[2]])}" inputmode="tel"></div>`).join('')}</div><div class="modal-actions"><button class="secondary" onclick="closeModal()">Cancel</button><button class="primary" id="saveStudent">Save Student</button></div>`);$('#sPhoto').onchange=e=>{const f=e.target.files[0];if(f){const r=new FileReader();r.onload=()=>$('#preview').innerHTML=`<img src="${r.result}" alt="">`;r.readAsDataURL(f)}};$('#saveStudent').onclick=()=>{const item={id:id||Date.now(),name:$('#sName').value.trim(),course:$('#sCourse').value.trim(),father:$('#sFather').value.trim(),fatherPhone:$('#sFatherPhone').value.trim(),mother:$('#sMother').value.trim(),motherPhone:$('#sMotherPhone').value.trim(),phone:$('#sPhone').value.trim(),photo:s.photo};const f=$('#sPhoto').files[0];if(!item.name)return alert('Enter student name.');const save=()=>{if(id)state.students[batch]=state.students[batch].map(x=>x.id===id?item:x);else state.students[batch].push(item);closeModal();studentDetails(batch,item.id)};if(f){const r=new FileReader();r.onload=()=>{item.photo=r.result;save()};r.readAsDataURL(f)}else save()}}
function counter(){let totals={Morning:0,Afternoon:0,Evening:0};Object.values(state.counters).forEach(x=>Object.keys(totals).forEach(t=>totals[t]+=x[t]));content.innerHTML=`<div class="section-head"><div><h2>Student Counter</h2><p>Total students requiring food</p></div><span class="batch-pill">Today</span></div><div class="summary"><div class="summary-card"><div class="sum-icon">☀</div><span>Morning</span><strong>${totals.Morning}</strong></div><div class="summary-card"><div class="sum-icon">☀</div><span>Afternoon</span><strong>${totals.Afternoon}</strong></div><div class="summary-card"><div class="sum-icon">☾</div><span>Evening</span><strong>${totals.Evening}</strong></div></div><div class="counter-grid">${Object.entries(state.counters).map(([b,x],i)=>`<article class="counter-card"><h3>${esc(b.replace(' — ',' · '))}</h3>${['Morning','Afternoon','Evening'].map(t=>`<div class="counter-row"><span class="counter-label">${t}</span><div class="stepper"><button data-minus="${esc(b)}|${t}">−</button><span class="count">${x[t]}</span><button data-plus="${esc(b)}|${t}">＋</button></div></div>`).join('')}<div class="counter-actions"><button class="secondary" data-reset="${esc(b)}">Reset</button><button class="primary" data-save="${esc(b)}">Save</button></div></article>`).join('')}</div>`;content.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>changeCounter(b.dataset.plus,1));content.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>changeCounter(b.dataset.minus,-1));content.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>{state.counters[b.dataset.reset]={Morning:0,Afternoon:0,Evening:0};counter()});content.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>alert('Counter saved locally. Supabase persistence can be connected next.'))}
function changeCounter(key,d){const [b,t]=key.split('|');state.counters[b][t]=Math.max(0,state.counters[b][t]+d);counter()}
function modal(inner){$('#modalRoot').innerHTML=`<div class="modal-backdrop" id="backdrop"><div class="modal">${inner}</div></div>`;$('#backdrop').onclick=e=>{if(e.target.id==='backdrop')closeModal()}}
function closeModal(){$('#modalRoot').innerHTML=''}
window.closeModal = closeModal;
window.login = login;
window.logout = logout;

startApp();
